### ISSUE TITLE
Feedback on week 12 project progress for CS2113-T14-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T14-3/main#132]
## Team progress for mid-`v1.4`
* Milestones setup:
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline 2019-11-11 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113-T14-3/main/pull/131 https://github.com/AY1920S1-CS2113-T14-3/main/issues/129 https://github.com/AY1920S1-CS2113-T14-3/main/issues/123 https://github.com/AY1920S1-CS2113-T14-3/main/issues/122 https://github.com/AY1920S1-CS2113-T14-3/main/issues/121 https://github.com/AY1920S1-CS2113-T14-3/main/issues/120 https://github.com/AY1920S1-CS2113-T14-3/main/issues/119 https://github.com/AY1920S1-CS2113-T14-3/main/issues/118 https://github.com/AY1920S1-CS2113-T14-3/main/issues/117 https://github.com/AY1920S1-CS2113-T14-3/main/issues/116 https://github.com/AY1920S1-CS2113-T14-3/main/issues/115 https://github.com/AY1920S1-CS2113-T14-3/main/issues/114 https://github.com/AY1920S1-CS2113-T14-3/main/issues/113 https://github.com/AY1920S1-CS2113-T14-3/main/issues/112 https://github.com/AY1920S1-CS2113-T14-3/main/issues/111 https://github.com/AY1920S1-CS2113-T14-3/main/issues/110 https://github.com/AY1920S1-CS2113-T14-3/main/issues/109 https://github.com/AY1920S1-CS2113-T14-3/main/issues/108 https://github.com/AY1920S1-CS2113-T14-3/main/issues/107 https://github.com/AY1920S1-CS2113-T14-3/main/issues/106 https://github.com/AY1920S1-CS2113-T14-3/main/issues/105 https://github.com/AY1920S1-CS2113-T14-3/main/issues/104 https://github.com/AY1920S1-CS2113-T14-3/main/issues/103 https://github.com/AY1920S1-CS2113-T14-3/main/issues/102 https://github.com/AY1920S1-CS2113-T14-3/main/issues/101 https://github.com/AY1920S1-CS2113-T14-3/main/issues/96 https://github.com/AY1920S1-CS2113-T14-3/main/issues/81 https://github.com/AY1920S1-CS2113-T14-3/main/issues/73 https://github.com/AY1920S1-CS2113-T14-3/main/issues/71 https://github.com/AY1920S1-CS2113-T14-3/main/issues/70 https://github.com/AY1920S1-CS2113-T14-3/main/issues/69 https://github.com/AY1920S1-CS2113-T14-3/main/issues/62 https://github.com/AY1920S1-CS2113-T14-3/main/issues/50 https://github.com/AY1920S1-CS2113-T14-3/main/issues/34 https://github.com/AY1920S1-CS2113-T14-3/main/issues/30 (:heavy_check_mark: well done!)
## Individual progress of @kevin996231 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/120 https://github.com/AY1920S1-CS2113-T14-3/main/issues/114 https://github.com/AY1920S1-CS2113-T14-3/main/issues/111 https://github.com/AY1920S1-CS2113-T14-3/main/issues/108 https://github.com/AY1920S1-CS2113-T14-3/main/issues/103 https://github.com/AY1920S1-CS2113-T14-3/main/issues/50 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @chelsea148629 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-3/main/pull/131 https://github.com/AY1920S1-CS2113-T14-3/main/issues/129 https://github.com/AY1920S1-CS2113-T14-3/main/issues/121 https://github.com/AY1920S1-CS2113-T14-3/main/issues/110 https://github.com/AY1920S1-CS2113-T14-3/main/issues/69 https://github.com/AY1920S1-CS2113-T14-3/main/issues/50 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @njw95 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/117 https://github.com/AY1920S1-CS2113-T14-3/main/issues/71 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tran-quang-thanh for mid-`v1.4`
* [ ] Merged updates to code (Java/FXML) files during the past 2 weeks (:exclamation: try to do by next milestone)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/118 https://github.com/AY1920S1-CS2113-T14-3/main/issues/112 https://github.com/AY1920S1-CS2113-T14-3/main/issues/102 https://github.com/AY1920S1-CS2113-T14-3/main/issues/101 https://github.com/AY1920S1-CS2113-T14-3/main/issues/71 https://github.com/AY1920S1-CS2113-T14-3/main/issues/30 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tessa-z for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/123 https://github.com/AY1920S1-CS2113-T14-3/main/issues/122 https://github.com/AY1920S1-CS2113-T14-3/main/issues/113 https://github.com/AY1920S1-CS2113-T14-3/main/issues/106 https://github.com/AY1920S1-CS2113-T14-3/main/issues/105 https://github.com/AY1920S1-CS2113-T14-3/main/issues/104 https://github.com/AY1920S1-CS2113-T14-3/main/issues/81 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @leowweixiang

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-07 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
