### ISSUE TITLE
Feedback on week 9 project progress for CS2113-T14-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T14-3/main#60]
## Team progress for `v1.2`
* [ ] Team PR created to the upstream repository with the title `[AY1920S1-CS2113-T14-3] Contact List Pro`(:exclamation:)
* Milestone `v1.2` properly managed:
   * [x] A suitable deadline 2019-10-14 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113-T14-3/main/issues/51 https://github.com/AY1920S1-CS2113-T14-3/main/issues/47 https://github.com/AY1920S1-CS2113-T14-3/main/pull/46 https://github.com/AY1920S1-CS2113-T14-3/main/pull/45 https://github.com/AY1920S1-CS2113-T14-3/main/pull/42 https://github.com/AY1920S1-CS2113-T14-3/main/issues/40 https://github.com/AY1920S1-CS2113-T14-3/main/issues/39 https://github.com/AY1920S1-CS2113-T14-3/main/issues/37 https://github.com/AY1920S1-CS2113-T14-3/main/issues/27 (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
   * [x] Code tagged as `v1.2`(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.2` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone v1.3 planned:
   * [x] A suitable deadline 2019-10-28 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113-T14-3/main/issues/54 https://github.com/AY1920S1-CS2113-T14-3/main/issues/52 https://github.com/AY1920S1-CS2113-T14-3/main/issues/33 (:heavy_check_mark: well done!)
## Individual progress of @kevin996231 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [ ] Has issues/PRs assigned for `v1.2` milestone (:exclamation:)
## Individual progress of @chelsea148629 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113-T14-3/main/pull/45 https://github.com/AY1920S1-CS2113-T14-3/main/pull/45 (:heavy_check_mark: well done!)
## Individual progress of @njw95 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/37 (:heavy_check_mark: well done!)
## Individual progress of @tran-quang-thanh for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113-T14-3/main/pull/42 https://github.com/AY1920S1-CS2113-T14-3/main/pull/42 (:heavy_check_mark: well done!)
## Individual progress of @tessa-z for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/51 https://github.com/AY1920S1-CS2113-T14-3/main/issues/40 https://github.com/AY1920S1-CS2113-T14-3/main/issues/39 (:heavy_check_mark: well done!)

Tutor: @leowweixiang

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-17 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
