### ISSUE TITLE
Feedback on week 10 project progress for CS2113-T14-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T14-3/main#82]
## Team progress for mid `v1.3`
* Milestone `v1.3` properly managed:
   * [x] A suitable deadline 2019-10-28 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113-T14-3/main/issues/79 https://github.com/AY1920S1-CS2113-T14-3/main/issues/70 https://github.com/AY1920S1-CS2113-T14-3/main/issues/69 https://github.com/AY1920S1-CS2113-T14-3/main/issues/68 https://github.com/AY1920S1-CS2113-T14-3/main/issues/67 https://github.com/AY1920S1-CS2113-T14-3/main/issues/66 https://github.com/AY1920S1-CS2113-T14-3/main/issues/65 https://github.com/AY1920S1-CS2113-T14-3/main/issues/62 https://github.com/AY1920S1-CS2113-T14-3/main/issues/61 https://github.com/AY1920S1-CS2113-T14-3/main/issues/54 https://github.com/AY1920S1-CS2113-T14-3/main/issues/52 https://github.com/AY1920S1-CS2113-T14-3/main/issues/43 https://github.com/AY1920S1-CS2113-T14-3/main/issues/36 https://github.com/AY1920S1-CS2113-T14-3/main/issues/33 https://github.com/AY1920S1-CS2113-T14-3/main/issues/29 (:heavy_check_mark: well done!)
* [x] New JAR released on GitHub.(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
## Individual progress of @kevin996231 for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/79 https://github.com/AY1920S1-CS2113-T14-3/main/issues/65 (:heavy_check_mark: well done!)
## Individual progress of @chelsea148629 for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/69 https://github.com/AY1920S1-CS2113-T14-3/main/issues/52 https://github.com/AY1920S1-CS2113-T14-3/main/issues/33 (:heavy_check_mark: well done!)
## Individual progress of @njw95 for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [ ] Has issues/PRs assigned for `v1.3` milestone (:exclamation: try to do by next milestone)
## Individual progress of @tran-quang-thanh for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/43 (:heavy_check_mark: well done!)
## Individual progress of @tessa-z for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113-T14-3/main/issues/79 https://github.com/AY1920S1-CS2113-T14-3/main/issues/67 https://github.com/AY1920S1-CS2113-T14-3/main/issues/66 https://github.com/AY1920S1-CS2113-T14-3/main/issues/36 https://github.com/AY1920S1-CS2113-T14-3/main/issues/29 (:heavy_check_mark: well done!)

Tutor: @leowweixiang

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-24 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
